FROM node:25-alpine3.21
WORKDIR /app
# crea la cartella corrente del container
COPY . .
# copio la cartella corrente del mio progetto nella cartella corrente del container
RUN npm install
# creato il container installo le dipendenze
EXPOSE 5173
