services:
  db:
    image: mysql
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: 'database'

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: ['py', 'app.py']